import { NextPage } from 'next'
import Page from '../components/Layout'

const Index: NextPage = () => {
  return (
    <Page title="onsplash" description="Generated by Create Next Stack.">
      <h1>Hello world!</h1>
    </Page>
  )
}

export default Index
